# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20160907_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('deposit', 'Depósito'), ('pagseguro', 'PagSeguro'), ('paypal', 'Paypal'), ('gerencianet', 'GerenciaNet')], default='deposit', max_length=20, verbose_name='Opção de Pagamento'),
        ),
    ]
