# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20160907_2327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdemItem',
            new_name='OrderItem',
        ),
    ]
