# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20160907_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart_key',
            field=models.CharField(db_index=True, max_length=40, null=True, verbose_name='Chave do Carrinho'),
        ),
    ]
